name: _Apps - Storefront
env:
  VERCEL_ORG_ID: ${{ secrets.RING_STOREFRONT_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.RING_STOREFRONT_VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
    paths:
      - apps/storefront/**
      - libs/cms/contentful/**
      - libs/commerce/swell/**
      - libs/logger/**
      - libs/ui/**
      - libs/ui-tokens/**

jobs:
  build-lint-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --immutable --immutable-cache --ignore-scripts

      - run: yarn format:check

      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_SERVER_TOKEN }}

      - run: yarn turbo run build-lib build lint test --filter=@ring/storefront... --api="http://127.0.0.1:9080" --token="${{ secrets.TURBO_SERVER_TOKEN }}" --team="ring"

  deploy-production:
    needs: [build-lint-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.RING_STOREFRONT_VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.RING_STOREFRONT_VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.RING_STOREFRONT_VERCEL_TOKEN }}
