name: _Apps - Storefront - Deploy Production

on:
  release:
    types: [published]

    tags:
      - '@ring/storefront-v*'
      - '@ring/contentful-v*'
      - '@ring/contracts-v*'
      - '@ring/logger-v*'
      - '@ring/swell-v*'
      - '@ring/ui-v*'
      - '@ring/ui-tokens-v*'

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
  SWELL_STORE_ID: ${{ secrets.SWELL_STORE_ID }}
  SWELL_SECRET_KEY: ${{ secrets.SWELL_SECRET_KEY }}
  VERCEL_ORG_ID: ${{ secrets.RING_STOREFRONT_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.RING_STOREFRONT_VERCEL_PROJECT_ID }}

jobs:
  build-lint-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --immutable --immutable-cache --ignore-scripts

      - run: yarn format:check

      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_SERVER_TOKEN }}

      - run: yarn turbo run build-lib build lint test --filter=@ring/storefront... --api="http://127.0.0.1:9080" --token="${{ secrets.TURBO_SERVER_TOKEN }}" --team="ring"

  deploy-production:
    needs: [build-lint-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.RING_STOREFRONT_VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.RING_STOREFRONT_VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.RING_STOREFRONT_VERCEL_TOKEN }}
